export const stockMoveColumns = [
  { accessorKey: "itemSeq", header: "Seq" },
  { accessorKey: "itemCd", header: "Item Code" },
  { accessorKey: "itemNm", header: "Item Name" },
  { accessorKey: "itemClsCd", header: "Class Code" },
  { accessorKey: "bcd", header: "Barcode" },
  { accessorKey: "pkg", header: "Pkg Qty" },
  { accessorKey: "pkgUnitCd", header: "Pkg Unit" },
  { accessorKey: "qty", header: "Qty" },
  { accessorKey: "qtyUnitCd", header: "Qty Unit" },
  { accessorKey: "itemExprDt", header: "Expiry Date" },
  { accessorKey: "prc", header: "Price" },
  { accessorKey: "splyAmt", header: "Supply Amt" },
  { accessorKey: "totDcAmt", header: "Discount" },
  { accessorKey: "taxblAmt", header: "Taxable Amt" },
  { accessorKey: "taxTyCd", header: "Tax Type" },
  { accessorKey: "taxAmt", header: "Tax Amt" },
  { accessorKey: "totAmt", header: "Total Amt" },
];
