export const importItemColumns = [
  { accessorKey: "taskCd", header: "Task Code" },
  { accessorKey: "dclDe", header: "Declaration Date" },
  { accessorKey: "itemSeq", header: "Item Seq" },
  { accessorKey: "dclNo", header: "Declaration No" },
  { accessorKey: "hsCd", header: "HS Code" },
  { accessorKey: "itemNm", header: "Item Name" },
  { accessorKey: "orgnNatCd", header: "Origin Code" },
  { accessorKey: "exptNatCd", header: "Export Code" },
  { accessorKey: "pkg", header: "Package Qty" },
  { accessorKey: "pkgUnitCd", header: "Package Unit" },
  { accessorKey: "qty", header: "Qty" },
  { accessorKey: "qtyUnitCd", header: "Qty Unit" },
  { accessorKey: "totWt", header: "Gross Wt" },
  { accessorKey: "netWt", header: "Net Wt" },
  { accessorKey: "spplrNm", header: "Supplier" },
  { accessorKey: "agntNm", header: "Agent" },
  { accessorKey: "invcFcurAmt", header: "Invoice Amt" },
  { accessorKey: "invcFcurCd", header: "Currency" },
  { accessorKey: "invcFcurExcrt", header: "Exchange Rate" },
];
